service: sambda

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2
  stage: dev
  environment:
    TESTNUM: 27
    TESTSTR: hello
    AUTH0_DOMAIN: pfernandom.auth0.com
    AUTH0_CLIENTID: L7YiTnpuzmfa1W9spj7fIpwXgHKzSmNX

resources:
  Resources:
    SambdaDB:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: users

functions:
  sayHello:
    handler: build/sayHello.sayHello
    events:
      - http:
          path: hello
          method: post
          integration: lambda
          request:
            template:
              passThrough: NEVER

  message:
    handler: build/message.message
    events:
      - http:
          path: message
          method: post
          integration: lambda
          request:
            template:
              passThrough: NEVER

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  # - serverless-webpack

custom:
#   webpackIncludeModules:
#     packagePath: './package.json'
  dynamodb:
      start:
        migrate: true
#   serverless-offline:
#     babelOptions:
#       presets: ["es2015", "stage-2"]